### ISSUE TITLE
Oh FFS, Really? (Alternate, PC title: Missing blog)

### ISSUE THREAD

**Issue by aclark4life** [plone/planet.plone.org#63]
@svx I don't want you to get the impression that I don't appreciate your contributions, because I absolutely do! But can you please try to tread a bit more lightly on some of the services you are maintaining that have been around for years before your arrival? :smile: (Get off my lawn, kids.)

E.g. 

<img width="1241" alt="screenshot 2017-12-22 08 37 44" src="https://user-images.githubusercontent.com/72164/34299941-c04c94b8-e6f3-11e7-9ae1-bd40fc95319d.png">

Here we have @zopyx updating his feed followed by a [commit](https://github.com/plone/planet.plone.org/commit/677636ff28b35bec68f0d266ce7056a1340b4927) in which the feeds.cfg is removed and replaced with (at the time) an empty feeds file,
 now apparently ["hand curated based on your whimsy"](https://github.com/plone/planet.plone.org/blob/master/planet/planet.ini).

**I mean, I get it.** And I'm aware of [this thread](https://community.plone.org/t/on-planet-plone-org/1186/10) and probably some other conversations happened about this too. But this _could have _and should have__ been handled so much better _from a software development perspective alone_, not to mention all the complexities of open source software communities :smile::

```
    $ git branch wip-theme
    $ git checkout wip-theme
    $ [Make drastic changes]
    $ git push
    $ hub browse (i.e. open github.com)
    [Create pull request]

```

Now anyone who was watching this repo would have gotten an email about your changes. Anyone not watching would probably need to be specifically mentioned, and some people wouldn't get the message, but at least those folks (myself included) would be able to check the repo and say "Oh, I wasn't watching this repo, my bad" instead of "Oh FFS, Really?" :smile:

End-o-rant, thanks for listening! And thanks for updating planet!

**Comment by svx** [comment]
I have no idea what you mean, the feed of @zopyx is still in the planet feed:

https://github.com/plone/planet.plone.org/blob/master/planet/planet.ini

Further on all of that was/is communicated always.
Yes sometimes mistakes happens, we are all humans, but maybe in place of sending this kind of cryptic criticism 'just' say in a constructive way that I forgot to migrate a feed ?

And yes, not all of the feeds got migrated yet, this was done on purpose because we want to cleanup and thus remove old and dead stuff.

Again, this is just a mail and issue away to fix.

It is alway easy to sit on the side and just give comments ...

**Comment by svx** [comment]
@aclark4life according to https://blog.aclark.net/ your last entry about Plone is from 2015/10/10, so yes you got not migrated because there was no Plone entry since more than a year !

Again there is no need for complaining via twitter that your blog got removed because of bad intentions or whatever.
This happened to a lot of blogs which had no recent (as in last entry about Plone is more than a year old).
This is/was done as part of cleaning out old and non active (Plone) blogs.  

Like already said above open a ticket with "hey I am still want to be on the blog" or whatever would more constructive.

**Comment by aclark4life** [comment]
@svx Thanks, FWIW: I know there's no ill-will towards me. Instead, I'm trying to make the _subtle point_ that there are ways to clean up without inadvertently pissing people off. I was actually just about to check ``feeds.cfg`` to remove my feed because I mostly blog to planet.python.org now-a-days… in other words, **I would have preferred to remove my own feed rather than have it removed for me.** Anyway, no worries and thanks again for your contributions.
